# create fitbit distance badges dataset
fitbit_distance_badges <- data.frame(
  badge = c(
    "Marathon",
    "Penguin March",
    "London Underground",
    "Hawaiian Islands",
    "Serengeti",
    "Italy",
    "New Zealand",
    "Pluto Width",
    "Great Barrier Reef",
    "Japan",
    "India",
    "Moon Width",
    "Pluto Pole-to-Pole",
    "Monarch Migration",
    "Sahara",
    "Mercury Width",
    "Moon Pole-to-Pole",
    "Nile",
    "Mars Width",
    "Mercury Pole-to-Pole",
    "Africa",
    "Great Wall",
    "Russian Railway",
    "Mars Pole-to-Pole",
    "Venus Width",
    "Earth Width",
    "Venus Pole-to-Pole",
    "Earth Pole-to-Pole",
    "Neptune Width",
    "Uranus Width",
    "Neptune Pole-to-Pole",
    "Uranus Pole-to-Pole",
    "Saturn Width",
    "Jupiter Width",
    "Saturn Pole-to-Pole",
    "Jupiter Pole-to-Pole",
    "Distance to Moon"),
  fitbit = c(
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE),
  distances_mi = c(
    26,
    70,
    250,
    350,
    500,
    736,
    990,
    1477,
    1600,
    1869,
    1997,
    2159,
    2320,
    2500,
    2983,
    3032,
    3391,
    4132,
    4221,
    4763,
    5000,
    5500,
    5772,
    6630,
    7521,
    7992,
    11814,
    12430,
    30775,
    31763,
    48341,
    49893,
    74898,
    88846,
    117650,
    139559,
    238900
  )
)

fitbit_distance_badges$distances_km <- round(fitbit_distance_badges$distances_mi * 1.60934)

# export 
usethis::use_data(fitbit_distance_badges, overwrite = TRUE)
