#' states_qualtrics
#'
#' A dataframe containing the state names (`state_label`) that correspond to the numeric state values (`state_value`) used by Qualtrics.
#' @export

states_qualtrics <- data.frame(state_value = 1:53, 
                               state_label = c("Alabama",
                                               "Alaska",
                                               "Arizona",
                                               "Arkansas",
                                               "California",
                                               "Colorado",
                                               "Connecticut",
                                               "Delaware",
                                               "District of Columbia",
                                               "Florida",
                                               "Georgia",
                                               "Hawaii",
                                               "Idaho",
                                               "Illinois",
                                               "Indiana",
                                               "Iowa",
                                               "Kansas",
                                               "Kentucky",
                                               "Louisiana",
                                               "Maine",
                                               "Maryland",
                                               "Massachusetts",
                                               "Michigan",
                                               "Minnesota",
                                               "Mississippi",
                                               "Missouri",
                                               "Montana",
                                               "Nebraska",
                                               "Nevada",
                                               "New Hampshire",
                                               "New Jersey",
                                               "New Mexico",
                                               "New York",
                                               "North Carolina",
                                               "North Dakota",
                                               "Ohio",
                                               "Oklahoma",
                                               "Oregon",
                                               "Pennsylvania",
                                               "Puerto Rico",
                                               "Rhode Island",
                                               "South Carolina",
                                               "South Dakota",
                                               "Tennessee",
                                               "Texas",
                                               "Utah",
                                               "Vermont",
                                               "Virginia",
                                               "Washington",
                                               "West Virginia",
                                               "Wisconsin",
                                               "Wyoming",
                                               "Other"))

